main: /usr/bin/python3
	mkdir /usr/app/papare
	touch /usr/app/papare/papare
	echo "#!/usr/bin/python3" > /usr/app/papare/papare
	echo "print('Hello World By Papare')" >> /usr/app/papare/papare
	chmod 755 /usr/app/papare/papare
	ln -sf /usr/app/papare/papare /usr/bin/papare
uninstall:
	rm -rvf /usr/app/papare
	rm -rvf /usr/bin/papare

